name: DNI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: dniTest
        with:
          configuration: test/phpunit.xml
          args: --coverage-text
